In [2]:
import numpy as np

In [11]:
matriz_edad= np.arange(3,27)

In [12]:
matriz_edad

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26])

In [43]:
Lista1 = [*range(0,5,1)]

In [44]:
Lista1

[0, 1, 2, 3, 4]

In [46]:
listas = Lista1+Lista1

In [48]:
matriz_2 = np.array(listas)

In [49]:
matriz_2

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [50]:
matriz_ascendente = np.sort(matriz_2)

In [51]:
matriz_ascendente

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])